#!/bin/bash
# Interactive setup: gather inputs, generate secrets/certs, load images, render configs.
# Writes .env at the repo root for docker-compose to consume.
#
# pipefail is intentionally omitted: the `tr -dc … </dev/urandom | head -c N` pattern
# in generate_secrets SIGPIPEs the upstream tr, which under pipefail returns 141 and
# `set -e` would kill the script silently right after the assignment.
set -eu

G_SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$G_SCRIPT_PATH/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; NC=$'\033[0m'

require_cmd() {
    for c in "$@"; do
        if ! command -v "$c" >/dev/null 2>&1; then
            echo "${RED}Missing required command: $c${NC}" >&2
            exit 1
        fi
    done
}

prompt_world_name() {
    while true; do
        read -r -p "World name shown in the server browser (1-50 chars): " WORLD_NAME
        if [ -n "$WORLD_NAME" ] && [ "${#WORLD_NAME}" -le 50 ]; then
            return
        fi
        echo "${RED}Invalid name; must be 1–50 characters.${NC}"
    done
}

prompt_world_region() {
    local regions=("Asia" "Europe" "North America" "Oceania" "South America")
    echo "Select FLS region:"
    select region in "${regions[@]}"; do
        if [ -n "${region:-}" ]; then
            WORLD_REGION="$region"
            return
        fi
        echo "${RED}Invalid selection.${NC}"
    done
}

prompt_fls_token() {
    while true; do
        read -r -p "Self-hosted FLS token (JWT from your dune account page): " FLS_TOKEN
        local payload
        payload=$(printf '%s' "$FLS_TOKEN" | jq -R 'split(".") | .[0:2] | map(@base64d) | map(fromjson)' 2>/dev/null || true)
        if [ -n "$payload" ]; then
            FLS_PLAYER_ID=$(printf '%s' "$payload" | jq -r '.[1].HostId' 2>/dev/null | tr '[:upper:]' '[:lower:]')
            if [ -n "$FLS_PLAYER_ID" ] && [ "$FLS_PLAYER_ID" != "null" ]; then
                return
            fi
        fi
        echo "${RED}Token doesn't look like a valid self-hosting JWT (missing HostId).${NC}"
    done
}

prompt_fls_api_key() {
    read -r -p "FLS API key UUID (press enter to use placeholder for testing): " FLS_API_KEY
    if [ -z "$FLS_API_KEY" ]; then
        FLS_API_KEY="00000000-0000-0000-0000-000000000000"
    fi
}

prompt_host_ip() {
    local default_ip
    default_ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')
    [ -z "$default_ip" ] && default_ip="127.0.0.1"
    read -r -p "Public/LAN IP players will connect to [$default_ip]: " HOST_IP
    HOST_IP="${HOST_IP:-$default_ip}"
}

prompt_display_name() {
    read -r -p "Browser display name [$WORLD_NAME]: " BROWSER_DISPLAY_NAME
    BROWSER_DISPLAY_NAME="${BROWSER_DISPLAY_NAME:-$WORLD_NAME}"
}

prompt_browser_password() {
    read -r -p "Optional server password (press enter for none): " BROWSER_PASSWORD
}

generate_secrets() {
    WORLD_UNIQUE_NAME="sh-${FLS_PLAYER_ID}-$(tr -dc 'a-z' </dev/urandom | head -c 6)"
    HOST_DATACENTER_ID="dune-${WORLD_REGION// /_}"
    POSTGRES_SUPER_PASS=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)
    POSTGRES_DUNE_PASS=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)
    RMQ_HTTP_TOKEN_AUTH_SECRET=$(openssl rand 64 | base64 -w0)
}

write_env_file() {
    # All values are double-quoted so that `source .env` works (a value like
    # WORLD_REGION="North America" would otherwise split on the space and run
    # `America` as a command). Docker compose's .env parser strips the quotes
    # on read, so interpolation in docker-compose.yml is unaffected.
    cat > "$ENV_FILE" <<EOF
# Generated by dune-setup/setup.sh on $(date -Iseconds)
# Edit by re-running setup.sh; manual edits won't be reflected in derived files
# (gateway-override.ini, UserEngine.ini) unless you re-run.

WORLD_NAME="${WORLD_NAME}"
WORLD_REGION="${WORLD_REGION}"
WORLD_UNIQUE_NAME="${WORLD_UNIQUE_NAME}"
HOST_IP="${HOST_IP}"
HOST_DATACENTER_ID="${HOST_DATACENTER_ID}"

FLS_TOKEN="${FLS_TOKEN}"
FLS_API_KEY="${FLS_API_KEY}"

POSTGRES_SUPER_PASS="${POSTGRES_SUPER_PASS}"
POSTGRES_DUNE_PASS="${POSTGRES_DUNE_PASS}"
RMQ_HTTP_TOKEN_AUTH_SECRET="${RMQ_HTTP_TOKEN_AUTH_SECRET}"

BROWSER_DISPLAY_NAME="${BROWSER_DISPLAY_NAME}"

# postgres-backup sidecar — adjust to taste. The defaults give one snapshot
# per hour with a 24-hour rolling window. After changing, re-create just
# the sidecar so it picks up the new values:
#   docker compose up -d --force-recreate postgres-backup
BACKUP_INTERVAL_SECONDS="3600"
BACKUP_RETENTION="24"
EOF
    chmod 600 "$ENV_FILE"
    echo "${GREEN}Wrote $ENV_FILE${NC}"
}

apply_browser_display_name() {
    # Uncomment + set the Bgd.ServerDisplayName line in the shared UserEngine.ini.
    # Game-servers re-read this on next restart.
    local ini="$G_SCRIPT_PATH/usersettings/UserEngine.ini"
    local escaped="${BROWSER_DISPLAY_NAME//\"/}"
    sed -i -E "s|^;?Bgd\\.ServerDisplayName=.*$|Bgd.ServerDisplayName=\"${escaped}\"|" "$ini"

    if [ -n "${BROWSER_PASSWORD:-}" ]; then
        local pw_escaped="${BROWSER_PASSWORD//\"/}"
        sed -i -E "s|^;?Bgd\\.ServerLoginPassword=.*$|Bgd.ServerLoginPassword=\"${pw_escaped}\"|" "$ini"
    fi
}

render_gateway_override() {
    # Substitute {PLACEHOLDERS} in the template using env vars we just generated.
    local src="$G_SCRIPT_PATH/gateway-override.ini.template"
    local dst="$G_SCRIPT_PATH/gateway-override.ini"
    sed \
        -e "s|{WORLD_UNIQUE_NAME}|${WORLD_UNIQUE_NAME}|g" \
        -e "s|{WORLD_NAME}|${WORLD_NAME}|g" \
        -e "s|{WORLD_REGION}|${WORLD_REGION}|g" \
        -e "s|{FLS_TOKEN}|${FLS_TOKEN}|g" \
        -e "s|{FLS_API_KEY}|${FLS_API_KEY}|g" \
        -e "s|{HOST_DATACENTER_ID}|${HOST_DATACENTER_ID}|g" \
        -e "s|{HOST_IP}|${HOST_IP}|g" \
        -e "s|{POSTGRES_DUNE_PASS}|${POSTGRES_DUNE_PASS}|g" \
        -e "s|{RMQ_HTTP_TOKEN_AUTH_SECRET}|${RMQ_HTTP_TOKEN_AUTH_SECRET}|g" \
        "$src" > "$dst"
    chmod 600 "$dst"
    echo "${GREEN}Rendered $dst${NC}"
}

generate_service_account() {
    # bg-director + game-servers expect a Kubernetes ServiceAccount mount at
    # /var/run/secrets/kubernetes.io/serviceaccount/{token,ca.crt,namespace}.
    # The orchestrator doesn't validate the token, but the K8s client libraries
    # need the files to exist and the CA to sign the orchestrator's TLS cert.
    local sa_dir="$G_SCRIPT_PATH/orchestrator/serviceaccount"
    mkdir -p "$sa_dir"
    openssl rand -base64 48 | tr -d '\n' > "$sa_dir/token"
    printf 'funcom-seabass-%s' "$WORLD_UNIQUE_NAME" > "$sa_dir/namespace"
    cp "$G_SCRIPT_PATH/certs/cacert.pem" "$sa_dir/ca.crt"
    chmod 644 "$sa_dir"/*
    echo "${GREEN}Wrote service-account at $sa_dir${NC}"
}

render_orchestrator_world() {
    # The orchestrator serves the BattleGroup CR via GET. Render the K8s
    # world-template.yaml with our env values so the orchestrator has the same
    # data the K8s setup would have written to the cluster.
    local src="$REPO_ROOT/server/scripts/setup/templates/world-template.yaml"
    local dst="$G_SCRIPT_PATH/orchestrator/world.yaml"
    if [ ! -f "$src" ]; then
        echo "${YELLOW}WARNING: $src not found; orchestrator will start with empty CR${NC}"
        return
    fi
    sed \
        -e "s|{WORLD_NAME}|${WORLD_NAME}|g" \
        -e "s|{WORLD_UNIQUE_NAME}|${WORLD_UNIQUE_NAME}|g" \
        -e "s|{WORLD_REGION}|${WORLD_REGION}|g" \
        -e "s|{WORLD_IMAGE_TAG}|1968181-0-shipping|g" \
        -e "s|{WORLD_POSTGRES_PASS}|${POSTGRES_SUPER_PASS}|g" \
        -e "s|{WORLD_DUNE_PASS}|${POSTGRES_DUNE_PASS}|g" \
        -e "s|{FLS_SECRET}|${FLS_TOKEN}|g" \
        -e "s|{RMQ_SECRET}|${RMQ_HTTP_TOKEN_AUTH_SECRET}|g" \
        "$src" > "$dst"
    chmod 644 "$dst"
    echo "${GREEN}Rendered $dst${NC}"
}

main() {
    require_cmd jq openssl docker ip
    echo "${GREEN}Dune Awakening — Docker Compose setup${NC}"

    if [ -f "$ENV_FILE" ]; then
        read -r -p "${YELLOW}.env already exists. Overwrite? [y/N]: ${NC}" yn
        case "$yn" in
            [yY]*) ;;
            *) echo "Aborted."; exit 0;;
        esac
    fi

    prompt_world_name
    prompt_world_region
    prompt_fls_token
    prompt_fls_api_key
    prompt_host_ip
    prompt_display_name
    prompt_browser_password

    generate_secrets
    write_env_file
    apply_browser_display_name
    render_gateway_override

    "$G_SCRIPT_PATH/generate-certs.sh"
    generate_service_account
    render_orchestrator_world
    "$G_SCRIPT_PATH/load-images.sh"

    echo
    echo "${GREEN}Setup complete.${NC}"
    echo "Next:"
    echo "  docker compose up -d                                    # start the always-on stack"
    echo "  docker compose --profile on-demand create               # materialize the 28 on-demand maps (stopped)"
    echo "  docker compose logs -f                                  # tail logs"
    echo "  docker compose down                                     # stop"
}

main "$@"
